"""initial schema

Creates the eleven core tables plus the FTS5 search index.

The FTS5 virtual table is not a model, because SQLAlchemy has no mapping for
one. It is an external-content index: it stores no copy of the message body,
only the inverted index, and reads the text back from the messages table by
rowid. The three triggers keep it in step with inserts, updates and deletes.


Revision ID: f4f23fa878da
Revises: 
Create Date: 2026-10-08 23:04:50.512299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f23fa878da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_verifications',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_verifications'))
    )
    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_verifications_phone_number'), ['phone_number'], unique=False)

    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_color', sa.String(length=8), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('contacts',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('contact_user_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name=op.f('fk_contacts_contact_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_contacts_owner_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('owner_id', 'contact_user_id', name='uq_contacts_owner_target')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_contact_user_id'), ['contact_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_owner_id'), ['owner_id'], unique=False)

    op.create_table('conversations',
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('avatar_color', sa.String(length=8), nullable=False),
    sa.Column('dm_key', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('disappearing_seconds', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.String(length=36), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(type = 'direct' AND dm_key IS NOT NULL) OR (type = 'group' AND dm_key IS NULL)", name=op.f('ck_conversations_dm_key_only_for_direct')),
    sa.CheckConstraint("type IN ('direct', 'group')", name=op.f('ck_conversations_conversation_type_known')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_message_id'], ['messages.id'], name=op.f('fk_conversations_last_message_id'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_dm_key'), ['dm_key'], unique=True)
        batch_op.create_index('ix_conversations_last_activity', ['last_activity_at'], unique=False)

    op.create_table('devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_message_id', sa.String(length=36), nullable=True),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name=op.f('ck_conversation_members_member_role_known')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_members_conversation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], name=op.f('fk_conversation_members_last_read_message_id'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_members_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_members')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_members_pair')
    )
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_members_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_members_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('envelope_hash', sa.String(length=64), nullable=False),
    sa.Column('reply_to_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("status IN ('sending', 'sent', 'delivered', 'read')", name=op.f('ck_messages_message_status_known')),
    sa.CheckConstraint("type IN ('text', 'image', 'file', 'system')", name=op.f('ck_messages_message_type_known')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], name=op.f('fk_messages_reply_to_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('sender_id', 'client_id', name='uq_messages_sender_client')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_messages_expires_at', ['expires_at'], unique=False, sqlite_where=sa.text('expires_at IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('attachments',
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_attachments_uploader_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_uploader_id'), ['uploader_id'], unique=False)

    op.create_table('message_receipts',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_receipts_message_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_receipts_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_receipts')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_receipts_pair')
    )
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('reactions',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_reactions_message_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reactions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_reactions_pair')
    )
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # --- full-text search -------------------------------------------------
    # External-content FTS5 index over message bodies. content='messages'
    # means the index stores no duplicate of the text; it reads through to
    # the base table, so the database does not carry every message twice.
    op.execute(
        """
        CREATE VIRTUAL TABLE messages_fts USING fts5(
            body,
            content='messages',
            content_rowid='rowid',
            tokenize='unicode61 remove_diacritics 2'
        )
        """
    )
    # Keep the index in step with the table. FTS5 external-content tables
    # require the 'delete' command to be issued with the OLD body before a
    # row changes, otherwise the index keeps stale terms.
    op.execute(
        """
        CREATE TRIGGER messages_fts_insert AFTER INSERT ON messages
        WHEN new.body IS NOT NULL
        BEGIN
            INSERT INTO messages_fts(rowid, body) VALUES (new.rowid, new.body);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER messages_fts_delete AFTER DELETE ON messages
        WHEN old.body IS NOT NULL
        BEGIN
            INSERT INTO messages_fts(messages_fts, rowid, body)
            VALUES ('delete', old.rowid, old.body);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER messages_fts_update AFTER UPDATE ON messages
        BEGIN
            INSERT INTO messages_fts(messages_fts, rowid, body)
            VALUES ('delete', old.rowid, old.body);
            INSERT INTO messages_fts(rowid, body)
            SELECT new.rowid, new.body WHERE new.body IS NOT NULL;
        END
        """
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- full-text search -------------------------------------------------
    op.execute("DROP TRIGGER IF EXISTS messages_fts_update")
    op.execute("DROP TRIGGER IF EXISTS messages_fts_delete")
    op.execute("DROP TRIGGER IF EXISTS messages_fts_insert")
    op.execute("DROP TABLE IF EXISTS messages_fts")

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reactions_message_id'))

    op.drop_table('reactions')
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_receipts_message_id'))

    op.drop_table('message_receipts')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_uploader_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_message_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index('ix_messages_expires_at', sqlite_where=sa.text('expires_at IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_members_conversation_id'))

    op.drop_table('conversation_members')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_last_activity')
        batch_op.drop_index(batch_op.f('ix_conversations_dm_key'))

    op.drop_table('conversations')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_contact_user_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_refresh_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_verifications_phone_number'))

    op.drop_table('phone_verifications')
    # ### end Alembic commands ###
