"""Message read and write shapes."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, model_validator

from app.models.enums import MessageStatus, MessageType
from app.schemas.common import UserPublic


class ReactionOut(BaseModel):
    emoji: str
    user_id: str
    display_name: str


class AttachmentOut(BaseModel):
    id: str
    file_name: str
    content_type: str
    size_bytes: int
    url: str
    width: int | None
    height: int | None
    thumbnail_url: str | None


class QuotedMessage(BaseModel):
    """The strip above a reply. Deliberately thin: just enough to render."""

    id: str
    sender_name: str | None
    body: str | None
    type: MessageType
    is_deleted: bool


class MessagePreview(BaseModel):
    """What the conversation list shows under the thread title."""

    id: str
    sender_id: str | None
    sender_name: str | None
    type: MessageType
    body: str | None
    status: MessageStatus
    is_deleted: bool
    event: str | None = None
    created_at: datetime


class MessageOut(BaseModel):
    id: str
    conversation_id: str
    sender: UserPublic | None
    type: MessageType
    body: str | None
    envelope_hash: str
    status: MessageStatus
    client_id: str
    reply_to: QuotedMessage | None
    reactions: list[ReactionOut]
    attachments: list[AttachmentOut]
    edited_at: datetime | None
    deleted_at: datetime | None
    expires_at: datetime | None
    is_forwarded: bool = False
    event: str | None = None
    #: Set only while the pin is live; an expired pin reads as unpinned.
    pinned_at: datetime | None = None
    pin_expires_at: datetime | None = None
    pinned_by: str | None = None
    created_at: datetime

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class MessagePage(BaseModel):
    """Cursor paging.

    `next_before` is the id to pass as `before` for the next page upwards.
    Null means the top of the thread has been reached.
    """

    messages: list[MessageOut]
    next_before: str | None
    has_more: bool


class SendMessageIn(BaseModel):
    #: Generated by the client before the request leaves the browser, so a
    #: retry is idempotent and the optimistic bubble can reconcile.
    client_id: str = Field(min_length=1, max_length=36)
    body: str | None = Field(default=None, max_length=8000)
    reply_to_id: str | None = None
    attachment_ids: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def require_content(self) -> SendMessageIn:
        if not (self.body and self.body.strip()) and not self.attachment_ids:
            raise ValueError("A message needs text or an attachment.")
        return self


class PinMessageIn(BaseModel):
    #: Signal offers 24 hours, 7 days, 30 days or Forever (null).
    duration_seconds: int | None = Field(default=604800, ge=60, le=31_536_000)


class ForwardIn(BaseModel):
    message_ids: list[str] = Field(min_length=1, max_length=30)
    conversation_ids: list[str] = Field(min_length=1, max_length=10)


class ReceiptOut(BaseModel):
    user: UserPublic
    delivered_at: datetime | None
    read_at: datetime | None


class MessageInfoOut(BaseModel):
    """The Info screen: the message, and per recipient when it arrived."""

    message: MessageOut
    receipts: list[ReceiptOut]


class EditMessageIn(BaseModel):
    body: str = Field(min_length=1, max_length=8000)


class ReactionIn(BaseModel):
    emoji: str = Field(min_length=1, max_length=16)


class MessageSearchHit(BaseModel):
    message_id: str
    conversation_id: str
    conversation_title: str
    sender_name: str | None
    body: str | None
    created_at: datetime
